### ISSUE TITLE
The blackberry.app properties are not read-only

### ISSUE THREAD

**Issue by ishneur** [blackberry-webworks/BB10-Webworks-API#12]
Description:
Try to set a blackberry.app property using JavaScript, e.g. blackberry.app.author = "Incorrect Author".

Expected: The "author" property in config.xml is not modified since it's read-only.

Actual: When calling blackberry.app.author, it's set to "Incorrect Author"

In the attached app:
1. Click on any of the properties - the correct value is shown
2. Click "Change config.xml values"
3. Click on this property again - an incorrect value is shown

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-API/GHI12.zip

Build used: http://mac-ci:9000/job/BB10-Webworks-Packager-next-app-api/

**Comment by erhorim** [comment]
Defect fixed by blackberry/BB10-Webworks-Packager#78
