### ISSUE TITLE
blackberry.event: "batterystatus" listener doesn't get triggered when plugging the wall USB cable for the first time

### ISSUE THREAD

**Issue by ishneur** [blackberry-webworks/BB10-Webworks-API#14]
Description:
1. Run the attached app
2. Click the first button to add a listener for "batterystatus"
3. Plug in the wall charger USB cable into the device

Expected: The event gets triggered and an alert is displayed.

Actual: The event doesn't get triggered.

It does get triggered on subsequent plug-ins and unplugs.

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-API/GHI14.zip

Build: http://mac-ci:9000/job/BB10-Webworks-Packager-next-event-api/

**Comment by tracyli** [comment]
This issue has been verified in the simulators in winxp & mac with build http://mac-ci:9000/job/BB10-Webworks-Framework-next-fix-execJSFirstTime/2/ and it has been fixed.

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#9
