### ISSUE TITLE
blackberry.event: Event handler doesn't get triggered if it's added for the 4th time, after adding and removing it 3 times

### ISSUE THREAD

**Issue by ishneur** [blackberry-webworks/BB10-Webworks-API#15]
Description:
1. Run the attached app
2. Click the first button to add an event handler for batterystatus
3. Create a batterystatus event (e.g. by plugging in the computer USB cable or changing the battery level) - the handler gets triggered as expected
4. Click the third button to remove the event handler
5. Unplug the cable - the handler doesn't get triggered as expected
6. Repeat steps 2-5 two more times
7. Click the first button (this is the 4th time)
8. Create a batterystatus event

Expected: The event handler gets triggered and an alert is displayed

Actual: The event handler doesn't get triggered

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-API/GHI14.zip

Build: http://mac-ci:9000/job/BB10-Webworks-Packager-next-event-api/

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#8
