### ISSUE TITLE
As a WebWorks developer, I have access to some system functionality and information useful for my app, part 2 

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#16]
This feature relates to the functionality found in current BlackBerry WebWorks SDKs under the blackberry.system namespace.  However, this grouping of features will be using Cordova style APIs, and will be 

**Acceptance Criteria**
1. The device OS (eg. 5.0, 7.0, 10 etc.) version is stored in the following property:
   - blackberry.device.version
2. The device model name will be stored in the following property:
   - blackberry.device.name
3. "blackberry.device" will be used as the feature id for whitelisting.

**Comment by rwmtse** [comment]
@kwallis @nukulb Whether we read device info from PPS or via BPS, we can only get:
1. device OS, which is "BlackBerry PlayBook OS" (whether it's PlayBook or not)
2. scm bundle, which is "10.0.4.171"

I don't see how we can get a "model" name yet.

**Comment by nukulb** [comment]
This is blocked because we don't what to return from here. @kwallis provide input and we will take it up later.

**Comment by nukulb** [comment]
@kwallis - what are we doing with this?

**Comment by kwallis** [comment]
blackberry.device.version can return the scm bundle number.
If we can't get the blackberry.device.name, we can defer that for now.

**Comment by nukulb** [comment]
This is still pending since we still don't have blackberry.device.name :(

**Comment by kwallis** [comment]
Closing this issue as it is no longer relevant
