### ISSUE TITLE
WW API not triggered in onLoad event

### ISSUE THREAD

**Issue by erhorim** [blackberry-webworks/BB10-Webworks-API#17]
Description:
The attached app shows an onLoad event that appends blackberry.app.author in a `<p>`.
Compile, load and launch app, and notice blackberry.app.author does not appear after "Description:"
Click blackberry.app.author button to show correct author text in an alert.
If the onLoad event were to append a plain "New Text", the onLoad event works properly.

Build: http://mac-ci:9000/job/BB10-Webworks-Packager/30/

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-API/GHIAPI17.zip

**Comment by nukulb** [comment]
this does not seem to use the deviceReady event.
WebWorks APIs will not trigger in the onLoad.
This by design
@kwallis to confirm and then close please.

**Comment by kwallis** [comment]
Confirm, expected behaviour that apis are not available until after the deviceReady event fires.
