### ISSUE TITLE
   "batterylow" and "batterycritical" events couldn't be triggered when the system enters a low or critical battery state once

### ISSUE THREAD

**Issue by tracyli** [blackberry-webworks/BB10-Webworks-API#18]
Steps to reproduce:
1. addEventListener to batterylow event
2. change battery level to be less than 15
3. removeEventListener to batterlow event
4. change battery level to be more or equal to 15
5. addEventListener to batterylow event
6. change battery level to be less than 15, which can be a different value from step2
     expected: batterylow event is triggered
     fact: batterylow event cannot be triggered

build: http://mac-ci:9000/job/BB10-Webworks-Packager-next-battery-low-critical-events/7/

**Comment by nukulb** [comment]
@kwallis seems important, how do you want to triage it?

**Comment by kwallis** [comment]
P1

----- Original Message -----

**Comment by jeffheifetz** [comment]
I believe this is desired behaviour.

Imagine the scenario where a developer sets a listener on one page, gets the event, then changes pages. On changing pages he removes the old listener and adds a new one. You would not expect him to receive the event the next time the battery went down, would you?

**Comment by tohman** [comment]
I've update the issue description with new entry for step 4, so now it can be seen as not expected behavior.

**Comment by jeffheifetz** [comment]
Just for curiosity, will it fire the second time for the same listener?

**Comment by kwallis** [comment]
There is also a scenario where the developer may attach a listener for the first time after low/critical has already been sent.  I am inclined to follow the following:

1) When the framework is first notified that the system falls below the low or critical threshold, all existing listeners are notified.
2)  No more notifications are sent from the framework to application code for those events until the system goes back above the threshold, then falls below again.
3) application developers, if they really need to know if they are in a low state before hitting critical, will need to also listen to batteryStatus events are handle that logic.

**Comment by tohman** [comment]
I think this is a scenario that describes an expected behavior.

**Comment by jeffheifetz** [comment]
For tracking purposes, @kwallis 's clarification applies to issue #6

**Comment by kwallis** [comment]
Yes, to be clear, the newly amended description of this issue clearly describes a bug that needs to be fixed.  P1

**Comment by tracyli** [comment]
verification got passed in mac&windows with build http://mac-ci:9000/job/BB10-Webworks-Packager-next-fix-18-addremovoeevent-reenter-threshold-trigger/1/.

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-Webworks-API#6
