### ISSUE TITLE
As a WebWorks developer, I can register for events that tell me when the connectivity of the device changes

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#20]
There will be two events, one to tell the developer the device is now connected to the internet, and one that indicates that network connectivity is lost.

**Acceptance Criteria**
1. These events will match the Cordova signatures for the online/offline events.
2. When the device is offline, and then gains internet connectivity, the online event should be fired.
3. When the device is online, and loses internet connectivity, the offline event should be fired.
4. To listen for the online event, developers can register using the blackberry.event.addEventListener method.
   eg. blackberry.event.addEventListener("online", onOnline);
5. To listen for the offline event, developers can register using the blackberry.event.addEventListener method.
   eg. blackberry.event.addEventListener("offline", onOffline);
6. The "blackberry.event" feature id will be used for whitelisting.

**Comment by jrogers** [comment]
WebKit on playbook already support for online/offline events and the navigator.isOnline property. Would these suffice? I would hate to see a bunch of work done to implement something that is already done.
See https://developer.mozilla.org/en/Online_and_offline_events

**Comment by kwallis** [comment]
Awesome, if our browser has this support then I'll close this requirement, as you say, no need to duplicate functionality. Thanks

----- Original Message -----

**Comment by kwallis** [comment]
Jeff, is the signature in our browser exactly the same as the one you reference on Mozilla?  I want to document these in our API reference.

**Comment by jrogers** [comment]
I think it's close we support the navigator attribute, and you can attach listeners to the windows object via addEventListener or using windows.online/offline=some function. Some tests at http://www.html5demos.com. We even supported this on BB7.

**Comment by kwallis** [comment]
Tracking as an issue against docs:

https://github.com/blackberry/WebWorks-API-Docs/issues/307
