### ISSUE TITLE
As a WebWorks developer, I can read, write, and navigate file system hierarchies from my application at runtime.

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#25]
File API  to allow navigation of the file system, read and write of files. This should match as closely as possible the Cordova file API.

**Acceptance Criteria**
1.    Overall strategy is to use the Cordova File API signatures
2.    Use "blackberry.io" as the feature id/namespace
3.  Limit to the host devices file system
4.  Allow listing of directories on the filesystem
5.  Allow listing of all files in a given directory
6.  Ability to create a new directory or file
7.  Ability to delete an existing directory and its sub-hierarchy
8.  Ability to delete an existing file
9.  Ability to read the contents of a file
10. Ability to write to a file, optionally creating the file if it does not exist
11. Ability to move a directory or file (this will allow rename as a usecase as well)
12. Ability to copy a file
13. Ability to get metadata information about a directory or file (need to understand what metadata is exposed by the system)
14. Able to get a listing of the contents of a directory

**Comment by kwallis** [comment]
Opened on the packager Repo.
https://github.com/blackberry/BB10-Webworks-Packager/issues/113

**Comment by kwallis** [comment]
Re-opening on this repo.  damn @nukulb

**Comment by nukulb** [comment]
So I think this is actually already supported by the browser's HTML5 support. We should already have this support right from the browser. 
I am skipping this User story till we can do a Gap analysis on if anything is missing. I believe FieSystem and FileReader are fully supported. 

http://dev.w3.org/2006/webapi/FileAPI/#filereader-interface
http://www.w3.org/TR/file-system-api/

http://html5test.com/ shows using FileReader and FileSystem

**Comment by nukulb** [comment]
@jeffheifetz - need this for the next sprint planning

**Comment by jeffheifetz** [comment]
The full API is not completely implemented but appears to be targeted for BB10.0.0.5. There is an issue tracking this internally

**Comment by nukulb** [comment]
@kwallis - please move this to the next milestone since its retargeeted to 10.0.06
