### ISSUE TITLE
As a WebWorks developer, I can transfer files from the device to a remote server and vice-versa

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#26]
This API allows a developer to transfer file content to and from the device from remote servers.  I.e. both upload and download.  This will leverage HTTP and HTTPS multi-part POST and GET.

**Acceptance Criteria**
1.  Overall strategy is to use the Cordova FileTransfer API signature.
2.    Use the "blackberry.io.filetransfer" namespace and feature id.
3.  Support both HTTP and HTTPS protocols
4.  Ability to upload a file from the local file system to a remote server
5.  Able to specify the mime type of the content to be uploaded
6.  Ability to download remote content to a file on the local file system
7.  Error handling provided for failed uploads or downloads
8.  HTTP response code and content should be accessible on uploads

**Comment by rwmtse** [comment]
@kwallis Just to double-check, is the feature id "blackberry.io" or "blackberry.io.filetransfer"?

**Comment by kwallis** [comment]
Blackberry.io.filetransfer

----- Original Message -----

**Comment by nukulb** [comment]
@kwallis - what should the chunk size be?
Should it be configurable?
Cordova simply defines true or false for chunking.

If true is selected there should be default chunk size. Do you care to make it configurable?

**Comment by adrianlee** [comment]
@nukulb @kwallis 

If we download a file and specify the target to be a directory that does not exist on the device. Should we create that directory?

Let's say `/accounts/1000/shared/camera/somedir/` where `/somedir/` does not exist.

**Comment by kwallis** [comment]
## Let's do that.  Please ensure that we handle the case where we can't create the required directory.  We should also test what happens if we try to create a dir in different perimeters and what that means.

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by adrianlee** [comment]
When creating a target directory, we can encounter the following problem:
- application has no access permissions to target and therefore unable to read or write to the target.

The current FileTransferError codes are :
- FileTransferError.FILE_NOT_FOUND_ERR = 1
- FileTransferError.INVALID_URL_ERR = 2
- FileTransferError.CONNECTION_ERR = 3

I'd like to propose two more constants to make it more clear when an error is thrown:
- FileTransferError.INVALID_TARGET_ERR = 4

**Comment by kwallis** [comment]
Looks good.

----- Original Message -----

**Comment by kwallis** [comment]
What are the Cordova chuck sizes?

At the last demo, we sort of punted and left them at 1MB.  Ideally this could be configurable, but if we are looking at significant delays then we can defer that to next release. 

----- Original Message -----

**Comment by adrianlee** [comment]
@kwallis I edited my last message. Can you reconfirm you are okay with it?

**Comment by kwallis** [comment]
If it is really related to a permissions issue, invalid target I don't think is accurate enough.  If permissions, then can we say something like PERMISSIONS_ERR?

----- Original Message -----

**Comment by adrianlee** [comment]
Cordova sets it to their chunk buffer size to 1MB for the Andriod. chunkedMode is not supported for iOS. I will add a chunk size parameter to the FileUploadOptions object. Should we call it chunkSize or chunkedSize?

Permission error makes more sense, I will make sure there is a description for this error in the docs for it. PERMISSION_ERR or PERMISSIONS_ERR?

**Comment by kwallis** [comment]
Chunksize

Permissions_err

----- Original Message -----

**Comment by ericpearson** [comment]
It doesn't look like the current API implementation respects the whitelist permissions when uploading. This should be fixed.

**Comment by nukulb** [comment]
@kwallis  whitelist issue - I assume we want this.

**Comment by kwallis** [comment]
Yes, we want to respect whitelist.
