### ISSUE TITLE
As a WebWorks developer, I can capture an image or a video from the device camera

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#27]
API to allow a developer to capture an image or a video from the device camera using the native camera application.  Will allow capturing one or multiple images, which are stored on the device file system. 

**Acceptance Criteria**
1.  Overall strategy is to use the Cordova Capture API signature.
2.     Use the "blackberry.capture" namespace and feature id
3.  Will invoke the native camera application.
4.  User can capture one or multiple pieces of content.  This is a parameter into the capture API
5.  Control is passed back to the WebWorks application when the user closes the native camera application.
6.  Success callback will pass back information on all the media files captured (location of file, metadata)
7.  If no content is captured before the action is terminated, the error callback is called

**Comment by rwmtse** [comment]
Some limitations I've noticed so far:
1. There is no way to control how many pictures the user will take once the camera app is launched, so whatever parameter they pass to limit the number of pics cannot really be enforced
2. From PPS, I could monitor the status of the camera, whether it's busy or idle. I suppose I can fire the callback when the camera's status change from busy to idle
3. I can get notification from PPS for each picture that has been taken. I wonder if it would be more natural if we fire the callback once for each picture taken

**Comment by kwallis** [comment]
Moved to Release Beta 4
