### ISSUE TITLE
As a WebWorks developer, I can listen for an event that will tell me when the connection type has changed

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#28]
### Acceptance Criteria
1. there is an event _connectionchange_ that the user can listen for.
   - eg. blackberry.event.addEventListener("_connectionchange_", onChange);
2. This event will fire whenever the system detects that the type of connection has changed.
3. The callback will receive two parameters, _oldType_ and _newType_.  oldType contains the connection type that was previously used, and newType contains the new connection type that is now being used by the system.
4. _blackberry.connection_ feature id will be used for whitelisting

**Comment by kwallis** [comment]
cc @nukulb

**Comment by miwong** [comment]
Should onChange have any parameters (e.g. the new connection type)?  Or should the user just call blackberry.connection.type themselves to get that information?

**Comment by kwallis** [comment]
## They can just query the connection.type property.  So don't think we need to return anything.

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by nukulb** [comment]
I prefer an event that comes back with the connection type. I would prefer, 
onChange(oldType, newType)

If the oldType is hard to get, its reasonable to simply have 
onChange(newType)

The user should not have to poll after getting the event.

**Comment by kwallis** [comment]
## That's fine, though this information will be duplicated since the connection.type is actually a property, not a callback.  I do also like the concept of returning the old type as well.

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by nukulb** [comment]
@kwallis - you need update the acceptance criteria with the new Id to whitelist

**Comment by kwallis** [comment]
updated

**Comment by dansilivestru** [comment]
Hey, looked at the code and it seems like it comes back with:
    info = {
        oldType: "foo",
        newtype: "bar"
    }

I might have misinterpreted that in the framework code though.

@nukulb can you please confirm?

**Comment by nukulb** [comment]
Clearly missed this, hopefully not too late.
The docs are here-
http://blackberry-webworks.github.com/WebWorks-API-Docs/WebWorks-API-Docs-next-BB10/view/blackberry.connection.html#.event:connectionchange

It comes back with just the info object which has old and new type

```
<script type="text/javascript">

function onChange(info) {
  alert("The network connection type used to be: " + info.oldType + " and is now: " + info.newType);
}

blackberry.event.addEventListener("connectionchange", onChange);

</script>
```

**Comment by dansilivestru** [comment]
Thanks for the clarification... Luckily that's how I coded it :-)
