### ISSUE TITLE
As a WebWorks developer, I can open a native-looking dialog to solicit feedback from the user

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#3]
This API allows a developer to open up a native-looking dialog with either standard buttons or custom buttons.  This will be used when feedback from the user is required.

**Acceptance Criteria**
1. This api should be in the blackberry.ui.dialog namespace, and the signatures should be compatible with the existing WebWorks API.
2. There should be a method standardAskAsync() that will create an asynchronous standard dialog to ask the user a question.
   - The 0-based index of the selected option will be returned to the optional callback parameter
   - This dialog should not block execution of the WebWorks application.
   - The buttons to show will be provided by a parameter (an array of integers).
   - The developer can control the title, size, and position of the dialog with an optional parameter.
3. There should be a method customeAskAsync() that will create an asynchronous custom dialog to ask the user a question.
   - The 0-based index of the selected option will be returned to the optional callback parameter
   - This dialog should not block execution of the WebWorks application.
   - The buttons to show will be provided by a parameter (an array of strings)
   - The developer can control the title, size, and position of the dialog with an optional parameter.
4. There can be only one dialog open at a time.  If a dialog is currently open and another request to open a dialog is made, the call will immediately fail silently, and the optional callback, if provided, will not be called.

**Comment by ericpearson** [comment]
The BPS dialog API seems support a lot more than what we have here. For example:

You can allow touch events to pass through the dialog whlie it is displayed.
You can show icons next to the dialog (Warning, Information, etc).
You have popup lists now so you can display multiple values and have the user select something.
There is a file browser dialog that lets you filter by file type, etc.
Login dialog to allow user authentication
Save file dialog

In addition to all of these you can show and hide a dialog programatically, even when the user has not provided any input, as well as update exiting dialogs with more information.

@jeffheifetz @nukulb

**Comment by nukulb** [comment]
simply copy the API from Snarf. No more is needed as of right now.

**Comment by kwallis** [comment]
Acceptance Criteria updated, number 4

**Comment by kwallis** [comment]
cc @tracyli

**Comment by nukulb** [comment]
@kwallis - you can open another one for the HTML dialog, I am closing this one as the AC is met
