### ISSUE TITLE
As a WebWorks developer, I can register to receive an event when the user swipes down from the top of the bezel

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#30]
### Acceptance Criteria
- There is an event *swipedown" that will be fired when the user completes a swipe down gesture from the top of the bezel
  -  eg. _blackberry.event.addEventListener("swipedown", swipedowncallback);_
- The event will be part of the _blackberry.app_ namespace, and _blackberry.app_ must be whitelisted for this event to be triggered.

**Comment by dansilivestru** [comment]
Is the event name "onswipedown"? convention will have it be "swipedown" and if we ever make it available on the document then you would write be able to write it like this too:

```
document.onswipedown = function () {};
```

Thoughts?

**Comment by kwallis** [comment]
Updated.

**Comment by dansilivestru** [comment]
Thanks, so, will we be able to register for this event off of document? Not sure that it makes sense, but figured I'd better ask :-)

**Comment by kwallis** [comment]
cc @nukulb

The framework doesn't support getting event registrations off of document.

## 

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369
