### ISSUE TITLE
As a WebWorks developer, I can find out what the current system language and regional settings are

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#35]
To support the requirement to allow the user to select UI language and regional formats independently of each other, the platform and applications must implement separate parameters for each of those preferences. Instead of one locale parameter, there will be a UI language parameter and a regional preference parameter. These may be completely different - UI language set to French (fr), regional preferences set to et_EE (Estonian as spoken in Estonia). The applications must display the translated strings in French in this case, while dates, times, numbers, calendars, etc., must be displayed with Estonian formats.
### Acceptance Criteria
- There is an API that allows the developer to query the system for language and region:
  - _blackberry.system.language()_ returns the current language setting for the device as a string
  - _blackberry.system.region()_ return the current region setting for the device as a string
- The developer can listen for a _languagechange_ event that will be triggered when the language setting changes
  - eg. _blackberry.event.addEventListener("languagechange", onLanguageChange);_
- The developer can listen for a _regionchange_ event that will be triggered when the region setting changes
  - eg. _blackberry.event.addEventListener("regionchange", onRegionChange);_ 
- _blackberry.system_ will be used for whitelisting for access to the query functions and the events.
- The following system UI components should be localized based on these settings:
  - Context Menu
  - Certificate authorization dialog
  - Invoke target selection UI

REF: PR168768

**Comment by kwallis** [comment]
Updates with more description, and to capture UI localization requirements.

cc @nukulb

**Comment by EricLeiLi** [comment]
@kwallis @nukulb I did a quick investigation on BB10, I can find the document about how to check locale, etc. but it doesn't seem to have anything related to "Region". Can anyone find any hint for me?

**Comment by EricLeiLi** [comment]
@kwallis @nukulb In BB10, it does have country and language for locale, so if you did mean language and country, we can do it.

**Comment by kwallis** [comment]
This is changing from what currently exists.  I will send the details offline.

----- Original Message -----

**Comment by gtanner** [comment]
Spec is showing methods but it looks like it was implemented as properties:

ie:

```
var value = blackberry.system.language();
```

but was coded as:

```
var value = blackberry.system.language;
```

what is correct?

**Comment by nukulb** [comment]
there is also navigator.language 
But eric li should be able to confirm 

------Original Message------

**Comment by gtanner** [comment]
Will navigator.language always be the same?

if it is, what is the point of having this API?

**Comment by kwallis** [comment]
Navigator.language does not give you the region.  So you still need system.region.  We have decided to leave system.language as well rather than taking it out.  Will be easier for discovery and could make things cleaner than being split in different namespaces.

Ken Wallis

Manager - Eclipse Tools
Research In Motion
905-629-4746 x14369

-----Original Message-----

**Comment by gtanner** [comment]
How is a value of : "en-CA" or "en-US" or "en-UK" not telling us the region as well as the language?

**Comment by nukulb** [comment]
the docs are here 

http://blackberry-webworks.github.com/WebWorks-API-Docs/WebWorks-API-Docs-next-BB10/view/blackberry.system.html

which enlists system.language and system.region as properties and not functions

**Comment by kwallis** [comment]
While they both return five letter values, they will actually be different values.  Ie. in the settings you would have something like:

Language: "English - United States" 
Region: "Canada"

And you get these for the WebWorks properties:
language: en_US

## region: en_CA

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by jeffheifetz** [comment]
Sorry to jump on this so late but just want to confirm what the purpose of blackberry.system.language.

I understand that we need a separate setting other than navigator.language since BB10 offers both language and region settings. But why do we need a duplicate language setting?
