### ISSUE TITLE
As a WebWorks developer, I can get the current system font setting and be notified of changes

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#36]
### Acceptance Criteria
- There is an API that allows the developer to query the system font setting:
  - _blackberry.system.getFontInfo()_ returns the current system font settings for the device
  - The current properties in the object are fontFamily and fontSize
- The developer can listen for a _fontchange_ event that will be triggered when the font setting changes
  - eg. _blackberry.event.addEventListener("fontchange", onFontChange);_
- _blackberry.system_ will be used for whitelisting for access to the query function and the event.
- The following system UI components should be automatically sized based on these settings:
  - Context Menu
  - Certificate authorization dialog
  - Invoke target selection UI

REF: PR161263

**Comment by tohman** [comment]
In addition to that I added blackberry.system.fontFamily() - returns current family font for the device.
Also callback for _fontsizechange_ event will receive two parameters family and size.

``` javascript
function onFontSizeChange(family, size) {
   .....
}
```

**Comment by kwallis** [comment]
@nukulb For the piece of this where the built-in UI needs to reflect the font changes, do you want to track that work in the individual pieces, or should this work be captured as part of this user story?

**Comment by tohman** [comment]
@kwallis We're designing the doc and need some more details for this.
1.  Do we want _fontFamily_ and _fontSize_ to be methods or properties? blackberry.system.fontFamily() vs blackberry.system.fontFamily
2. Since the event would be for both family and size should we call it _fontchange_ instead of _fontsizechange_?
3. Do we want to combine getFont and getFamily to one _getFontInfo_ to return object contais family and size of the font?

**Comment by kwallis** [comment]
I like the object approach, will make it easier if we need to add additional options in the future that might be exposed.

## 

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369

**Comment by kwallis** [comment]
Issue description updated

**Comment by EricLeiLi** [comment]
in current blackberry.system, the event for language change and region change is languagechanged and regionchanged, i wonder if we should use fontchanged or we change the above two to xxxchange or we leave it for later.

**Comment by nukulb** [comment]
fontchanged makes more sense to me.

**Comment by kwallis** [comment]
Agreed

## 

Ken Wallis

Product Manager – BlackBerry WebWorks

Research In Motion

(905) 629-4746 x14369
