### ISSUE TITLE
As a WebWorks developer, I can query the system for the IMSI

### ISSUE THREAD

**Issue by kwallis** [blackberry-webworks/BB10-Webworks-API#42]
### Acceptance Criteria
- blackberry.identity.IMSI will contain the IMSI
- blackberry.identity will be used for whitelisting.
- Look at the deviceproperties PPS object

**Comment by tohman** [comment]
I've implemented IMSI, apparently IMSI  won't be user facing also I added IMEI.
It requires same whitelisting as for blackberry.identity.uuid
The usage: blackberry.identity.IMEI
