### ISSUE TITLE
Browser cannot be invoked with a URL which doesn't contain a protocol

### ISSUE THREAD

**Issue by ishneur** [blackberry-webworks/BB10-Webworks-API#7]
Description:
Try to invoke the browser with a URL which doesn't have a protocol, e.g.:
        var args = new blackberry.invoke.BrowserArguments("www.rim.com");
        blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, args);

Expected: Browser can be invoked with this URL

Actual: Browser doesn't open

In the attached app, click the button "www.rim.com".

Build: http://mac-ci:9000/job/BB10-Webworks-Packager-next-invoke-api/

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-Packager/API_GHI7.zip

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#55
