### ISSUE TITLE
Browser cannot be invoked when the second parameter is not specified or is "null"/undefined for blackberry.invoke.invoke

### ISSUE THREAD

**Issue by ishneur** [blackberry-webworks/BB10-Webworks-API#8]
Description:

Try to invoke the browser by calling the invoke API as follows:
1. blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER)
2. blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, null)
3. blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, undefined)

Expected: The browser is invoked opening a blank page (Snarf behavior)

Actual: Error 404 is shown

In the attached app, click the following buttons:
"blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER)"
"blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, null)"
"blackberry.invoke.invoke(blackberry.invoke.APP_BROWSER, undefined)"

Attachment: https://github.com/downloads/blackberry-webworks/BB10-Webworks-Packager/API_GHI7.zip

Build: http://mac-ci:9000/job/BB10-Webworks-Packager-next-invoke-api/

**Comment by erhorim** [comment]
Defect fixed by blackberry-webworks/BB10-WebWorks-Framework#55
